---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: community.docker
    version: '>=3.0.0'
  - name: community.crypto
    version: '>=2.0.0'
